name: Suggest a change (newest)
name: 💡 Suggest a change
description: Report something wrong, suggest improvements or ideas for new guidance.
title: "[Change]: "
labels:
  - change
  - content
  - fix

body:
  - type: markdown
    attributes:
      value: |
      **Note** This is an open source repo -  

        * Before you file an issue read the [Contributing guide](https://github.com/GIGCymru/dhcw-software-engineering-handbook/blob/main/CONTRIBUTING.md) and 
        [Code of Conduct](https://github.com/GIGCymru/dhcw-software-engineering-handbook/blob/main/CODE_OF_CONDUCT.md)
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/github/docs/issues)
      Thanks for helping improve the handbook.

  - type: checkboxes
    id: conduct
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the [Code of Conduct](https://github.com/GIGCymru/dhcw-software-engineering-handbook/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: dropdown
    id: change_type
    attributes:
      label: Describe the change
      options:
        - Fix something (e.g. typos or broken links)
        - Suggest an improvement
        - Add new content
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What needs to change?
      description: Tell us what is wrong, unclear, or missing
      placeholder: e.g. Broken link in doc/index.md or “Add guidance on feature branching in Using Source Control”
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this change useful?
      description: Optional. Who would benefit and how?
