blank_issues_enabled: false

contact_links:
  - name: Content idea
    url: /issues/new?template=improve-existing-documentation.yml
    about: Suggest new content or improvements

  - name: Documentation fix
    url: /issues/new?template=fix-existing-documentation.yml
    about: Report an issue with existing documentation
